apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ct-signal
  namespace: catalant-signal
spec:
  sslPolicy: prod-ssl-policy
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
