#!/usr/bin/env python3
"""Generate the nginx security-headers snippet with CSP hashes for every inline
<script> across all HTML files in the content tree.

Usage: gen_csp.py <src-dir> <out.conf>
"""

import base64
import hashlib
import pathlib
import re
import sys

STYLE_SRC = "'unsafe-inline'"
CONNECT_SRC = "https://docs.google.com"

SCRIPT_RE = re.compile(r"<script\b([^>]*)>(.*?)</script>", re.IGNORECASE | re.DOTALL)
SRC_RE = re.compile(r"\bsrc\s*=", re.IGNORECASE)
HTML_GLOBS = ("*.html", "*.htm")


def sha256_source(body: str) -> str:
    digest = hashlib.sha256(body.encode("utf-8")).digest()
    return f"'sha256-{base64.b64encode(digest).decode('ascii')}'"


def html_files(root: pathlib.Path) -> list[pathlib.Path]:
    found: list[pathlib.Path] = []
    for pattern in HTML_GLOBS:
        found.extend(root.rglob(pattern))
    return sorted(p for p in found if p.is_file())


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write(f"usage: {sys.argv[0]} <src-dir> <out.conf>\n")
        return 2

    root = pathlib.Path(sys.argv[1])
    out_path = sys.argv[2]

    if not root.is_dir():
        sys.stderr.write(f"error: {root} is not a directory\n")
        return 1

    pages = html_files(root)
    if not pages:
        sys.stderr.write(f"error: no HTML files under {root}\n")
        return 1

    hashes: dict[str, list[str]] = {}
    external = False

    for page in pages:
        html = page.read_text(encoding="utf-8")
        for attrs, body in SCRIPT_RE.findall(html):
            rel = page.relative_to(root).as_posix()
            if SRC_RE.search(attrs):
                sys.stderr.write(
                    f"error: {rel} has an external <script src=...>; "
                    "add its origin to script-src in this script\n"
                )
                external = True
                continue
            hashes.setdefault(sha256_source(body), []).append(rel)

    if external:
        return 1
    if not hashes:
        sys.stderr.write("error: no inline <script> found; refusing to emit a CSP\n")
        return 1

    csp = "; ".join(
        [
            "default-src 'none'",
            f"script-src {' '.join(sorted(hashes))}",
            f"style-src {STYLE_SRC}",
            "img-src 'self' data:",
            f"connect-src {CONNECT_SRC}",
            "base-uri 'none'",
            "form-action 'none'",
            "frame-ancestors 'none'",
            "object-src 'none'",
            "manifest-src 'self'",
            "worker-src 'none'",
            "upgrade-insecure-requests",
        ]
    )

    permissions = (
        "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), "
        "camera=(), display-capture=(), document-domain=(), encrypted-media=(), "
        "geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), "
        "payment=(), picture-in-picture=(), publickey-credentials-get=(), "
        "screen-wake-lock=(), serial=(), usb=(), xr-spatial-tracking=()"
    )

    lines = [
        "# generated by scripts/gen_csp.py -- do not edit",
        f'add_header Content-Security-Policy "{csp}" always;',
        'add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;',
        'add_header X-Content-Type-Options "nosniff" always;',
        'add_header X-Frame-Options "DENY" always;',
        'add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
        'add_header Cross-Origin-Opener-Policy "same-origin" always;',
        'add_header Cross-Origin-Resource-Policy "same-origin" always;',
        f'add_header Permissions-Policy "{permissions}" always;',
        'add_header X-Permitted-Cross-Domain-Policies "none" always;',
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    sys.stderr.write(
        f"gen_csp.py: {len(pages)} page(s), {len(hashes)} script hash(es) -> {out_path}\n"
    )
    for h, where in sorted(hashes.items()):
        sys.stderr.write(f"  {h}  {', '.join(where)}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
